### PR TITLE
Add starting Hazelcast cluster template

### PR DESCRIPTION
**Pull request by enozcan**
Related: https://github.com/hazelcast-guides/hazelcast-embedded-microprofile/issues/19

@cangencer @leszko Could you please take a look and let me know if there could be any other option? The template will look like:
start-cluster

### CODE REVIEW

**Comment by cangencer** [comment]
@yunussandikci could you review the cloud instructions?

**Comment by yunussandikci** [comment]
I don’t know target audience of this guide but, instead of talking about `discovery token` etc. we can say that,

You can easily create a Hazelcast Cluster on [Hazelcast Cloud](https://cloud.hazelcast.com/) with just a few clicks. See the [Getting Started](https://docs.cloud.hazelcast.com/docs/getting-started) documentation for details.


@enozcan @cangencer What do you think?

**Comment by cangencer** [comment]
yep I think that's enough.

**Comment by enozcan** [comment]
That's way better. Updating accordingly. Thanks

**Comment by leszko** [comment]
Technically speaking, here is a list of all possible ways of starting hazelcast: https://docs.hazelcast.org/docs/latest/manual/html-single/#installing-hazelcast-imdg

But I think these 4 should be enough for the guides.

**Comment by enozcan** [comment]
Let me add this doc link after these 4 options like "Also see all options" or something. Thank you all for suggestions.

**Pull request merged**
